loadBalancerIP: 10.96.11.1
service:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
rbac:
  enabled: true
dashboard:
  enabled: true
  domain: traefik.hmcts.net

      