---
apiVersion: v1
kind: Namespace
metadata:
  name: osba-sb-test
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: servicebus-service-instance
  namespace: osba-sb-test
spec:
  clusterServiceClassExternalName: azure-servicebus
  clusterServicePlanExternalName: premium
  parameters:
    location: 'uksouth'
    resourceGroup: 'timw-aks-rg'
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: servicebus-binding
  namespace: osba-sb-test
spec:
  instanceRef:
    name: servicebus-service-instance
  secretName: servicebus-secret