---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhubarb-frontend
  namespace: cnp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhubarb-frontend
  template:
    metadata:
      labels:
        app: rhubarb-frontend
    spec:
      containers:
      - image: hmctssandbox.azurecr.io/hmcts/custard-frontend
        name: rhubarb-frontend
        env:
          - name: RECIPE_BACKEND_URL
            value: "http://rhubarb-backend-service"
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 1337
          name: http
        imagePullPolicy: Always
---
#
# Rhubarb Service
#
apiVersion: v1
kind: Service
metadata:
  name: rhubarb-frontend-service
  namespace: cnp
  labels:
    app: rhubarb-backend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 1337
  selector:
    app: rhubarb-frontend
---
#
# Ingress
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rhubarb-frontend-ingress
  namespace: cnp
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /rhubarb-frontend
        backend:
          serviceName: rhubarb-frontend-service
          servicePort: 80