apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-tasks
  namespace: locust
data:
  locust-tasks: |
    from locust import HttpLocust, TaskSet, task

    class UserBehavior(TaskSet):
        @task(1)
        def health(self):
            self.client.get("/health")

    class WebsiteUser(HttpLocust):
        task_set = UserBehavior
        min_wait = 1000
        max_wait = 2000
